version: 1
disable_existing_loggers: False
 
# Define format of output logs (named 'simple').
formatters:
    simple:
        format: "%(asctime)s -%(levelname)s- %(message)s"
 
handlers:
    # Create rotating file handler using 'simple' format.

    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        maxBytes: 1048576 # 1MB
        backupCount: 5
        encoding: utf8
 
root:
 
    level: INFO
    handlers: [file_handler, console]
